<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Runubala" failures="1" tests="5" name="com.nt.partice.AlwaysRun_partice" time="0.008" errors="0" timestamp="2022-09-12T23:02:53 IST" skipped="1">
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Begin" time="0.002">
    <failure message="We are failing the testcase" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: We are failing the testcase
at org.testng.Assert.fail(Assert.java:99)
at com.nt.partice.AlwaysRun_partice.Begin(AlwaysRun_partice.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Begin -->
  <system-out/>
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Ready" time="0.002"/>
  <system-out/>
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Steady" time="0.002"/>
  <system-out/>
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Running" time="0.002"/>
  <system-out/>
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="End" time="0.000">
    <skipped/>
  </testcase> <!-- End -->
  <system-out/>
</testsuite> <!-- com.nt.partice.AlwaysRun_partice -->
